name: Open PR
description: Opens a pull request
inputs:
  template:
    description: The path to the template file
    required: true
  existing-changes:
    description: The body of existing changes
    required: false
  github-token:
    description: The GitHub token
    required: true
  base-branch:
    description: The base branch for the pull request
    required: true
  branch-with-changes:
    description: The branch with the changes
    required: true

runs:
  using: composite
  steps:
    - name: Check if PR already exists
      id: check-pr-exists
      run: |
        gh pr list -H ${{inputs.branch-with-changes}} -B ${{inputs.base-branch}} --json number --jq '.[] | select(.number != null)' > pr-number.json
        if [ -s pr-number.json ]; then
          echo "PR already exists"
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "PR does not exist"
          echo "result=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash

    - name: Set default existing changes
      if: steps.check-pr-exists.outputs.result == 'false' && inputs.existing-changes == ''
      run: |
        echo "existing-changes<<EOF" >> $GITHUB_ENV
        echo "<!-- List out the changes -->" >> $GITHUB_ENV
        echo "<!-- - tls-111(fix): Fixed xyz -->" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    # - name: Set inputted existing changes
    #   if: steps.check-pr-exists.outputs.result == 'false' && inputs.existing-changes != ''
    #   run: |
    #     echo "existing-changes=${{ inputs.existing-changes }}" >> $GITHUB_ENV
    #   shell: bash

    - name: Log existing changes
      if: steps.check-pr-exists.outputs.result == 'false'
      run: |
        echo "Existing changes: ${{ env.existing-changes }}"
      shell: bash

    - name: Write PR body
      if: steps.check-pr-exists.outputs.result == 'false'
      id: write-pr-body
      uses: ./.github/actions/open-pr/write-pr-body
      with:
        template: ${{ inputs.template }}
        vars: |
          baseBranchName: ${{ inputs.base-branch }}
          existingChanges: ${{ env.existing-changes }}

    - name: Read PR body from file
      if: steps.check-pr-exists.outputs.result == 'false'
      id: read_pr_body
      run: |
        PR_BODY=$(cat ${{ steps.write-pr-body.outputs.pr-body-file-env-name }})
        echo "PR_BODY<<EOF" >> $GITHUB_ENV
        echo "$PR_BODY" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    - name: Create Pull Request
      if: steps.check-pr-exists.outputs.result == 'false'
      run: gh pr create -B ${{inputs.base-branch}} -H ${{inputs.branch-with-changes}} --title '${{inputs.branch-with-changes}} -> ${{inputs.base-branch}}' --body '${{env.PR_BODY}}'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
