name: Open PR
description: Opens a pull request
inputs:
  template:
    description: The path to the template file
    required: true
  github-token:
    description: The GitHub token
    required: true
  base-branch:
    description: The base branch for the pull request
    required: true
  branch-with-changes:
    description: The branch with the changes
    required: true

runs:
  using: composite
  steps:
    - name: Check if PR already exists
      id: check-pr-exists
      run: |
        gh pr list -H ${{inputs.branch-with-changes}} -B ${{inputs.base-branch}} --json number --jq '.[] | select(.number != null)' > pr-number.json
        if [ -s pr-number.json ]; then
          echo "PR already exists"
          echo "result=true" >> $GITHUB_OUTPUT
        else
          echo "PR does not exist"
          echo "result=false" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash


    - name: Write PR body
      if: steps.check-pr-exists.outputs.result == 'false'
      id: write-pr-body
      uses: ./.github/actions/open-pr/write-pr-body
      with:
        template: ${{ inputs.template }}
        vars: |
          baseBranchName: ${{ inputs.base-branch }}

    - name: Read PR body from file
      if: steps.check-pr-exists.outputs.result == 'false'
      id: read_pr_body
      run: |
        PR_BODY=$(cat ${{ steps.write-pr-body.outputs.pr-body-file-env-name }})
        echo "PR_BODY<<EOF" >> $GITHUB_ENV
        echo "$PR_BODY" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash

    #  Check if the base branch exists
    - name: Check if base branch exists
      if: steps.check-pr-exists.outputs.result == 'false'
      id: check-base-branch-exists
      run: |
        output=$(git ls-remote --heads origin ${{inputs.base-branch}})
        if [ -z "$output" ]; then
        echo "Base branch does not exist"
        echo "result=false" >> $GITHUB_OUTPUT
        else
          echo "Base branch exists"
          echo "result=true" >> $GITHUB_OUTPUT
        fi
      shell: bash

    # If the base branch doesn't exist, create it
    - name: Create base branch
      if: steps.check-pr-exists.outputs.result == 'false' && steps.check-base-branch-exists.outputs.result == 'false'
      uses: ./.github/actions/create-branch
      with:
        branch-name: ${{ inputs.base-branch }}
        base-branch: main
        github-token: ${{ inputs.github-token }}
      # run: |
      #   echo "Creating base branch ${{inputs.base-branch}}"
      #   git fetch origin
      #   git checkout main
      #   git pull origin main
      #   git checkout -b ${{inputs.base-branch}}
      #   git push -u origin ${{inputs.base-branch}}
      #   git checkout ${{inputs.branch-with-changes}}

      # env:
      #   GITHUB_TOKEN: ${{ inputs.github-token }}
      # shell: bash


    - name: Create Pull Request
      if: steps.check-pr-exists.outputs.result == 'false'
      run: gh pr create -B ${{inputs.base-branch}} -H ${{inputs.branch-with-changes}} --title '${{inputs.branch-with-changes}} -> ${{inputs.base-branch}}' --body '${{env.PR_BODY}}'
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
