name: Write PR Body
description: Writes the PR body given a list of variables and a template file

inputs:
  template:
    description: The path to the template file
    required: true
  vars:
    description: The variables to use in the template
    required: true

outputs:
  pr-body-file-env-name:
    description: The file path of the rendered PR body file
    value: ${{ steps.return-pr-body-file-path.outputs.pr-body-file-env-name }}

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate random number
      id: random-number
      run: echo "RANDOM_NUMBER=$(($RANDOM % 10000))" >> $GITHUB_ENV
      shell: bash

    - name: Render PR template
      id: pr-body-template
      uses: chuhlomin/render-template@v1.4
      with:
        template: ${{ inputs.template }}
        vars: ${{ inputs.vars }}
        result_path: "${{ env.RANDOM_NUMBER }}-rendered-md.md"
    - name: Return PR body file path
      id: return-pr-body-file-path
      run: echo "pr-body-file-env-name=${{ env.RANDOM_NUMBER }}-rendered-md.md" >> $GITHUB_OUTPUT
      shell: bash