name: Increment Version
description: Increments the build number or version number in the app.json file depending on the input

inputs:
  increment-version:
    description: Whether to increment the version number (true or false)
    required: false
    default: "false"
  increment-version-type:
    description: The type of value to increment (major or minor or patch)
    required: false
    default: "minor"
  increment-build-number:
    description: Whether to increment the build number (true or false)
    required: false
    default: "false"
  github-admin-token:
    description: The GitHub token with admin permissions
    required: true
  branch-to-push-changes-to:
    description: The branch to push the changes to
    required: true

runs:
  using: composite
  steps:
    - name: Get current version and build number
      id: get-current-version-info
      uses: ./.github/actions/get-current-version-info
      
    - name: Get new version
      if: inputs.increment-version == 'true'
      id: get-new-version
      uses: ./.github/actions/increment-version/get-new-version
      with:
        current-version: ${{ steps.get-current-version-info.outputs.version }}
        increment-version-type: ${{ inputs.increment-version-type }}

    - name: Set new version
      if: inputs.increment-version == 'true'
      id: set-new-version
      run: |
        jq --arg newVersion "${{ steps.get-new-version.outputs.new-version }}" '.expo.version = $newVersion' app.json > temp.json && mv temp.json app.json
        echo "version=${{ steps.get-new-version.outputs.new-version }}" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Reset build number
      id: reset-build-number
      if: inputs.increment-version == 'true'
      run: |
        jq --arg newBuildNumber "1" '.expo.ios.buildNumber = $newBuildNumber' app.json > temp.json && mv temp.json app.json
        echo "build-number=1" >> $GITHUB_OUTPUT
      shell: bash

    - name: Increment build number
      id: increment-build-number
      if: inputs.increment-build-number == 'true' && inputs.increment-version == 'false'
      run: |
        currentBuildNumber=${{ steps.get-current-version-info.outputs.build-number }}
        if [ -z "$currentBuildNumber" ]; then
          currentBuildNumber=0
        fi
        newBuildNumber=$((currentBuildNumber + 1))
        jq --arg newBuildNumber "$newBuildNumber" '.expo.ios.buildNumber = $newBuildNumber' app.json > temp.json && mv temp.json app.json
        echo "build-number=$newBuildNumber" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get Commit Message
      id: get-commit-message
      if: inputs.increment-version == 'true' || inputs.increment-build-number == 'true'
      run: |

        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        commit_message="Incremented"

        if [ "${{ inputs.increment-version }}" == "true" ]; then
          commit_message+=" version"
        fi

        if [ "${{ inputs.increment-build-number }}" == "true" ]; then
          if [ "$commit_message" != "Incremented" ]; then
            commit_message+=" and"
          fi
          commit_message+=" build number"
        fi


        commit_message+="."

        echo "commit-message=$commit_message" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create a new tree
      id: create-tree
      if: inputs.increment-version == 'true' || inputs.increment-build-number == 'true'
      run: |
        BASE_TREE=$(git rev-parse HEAD)
        CONTENT=$(cat app.json | jq -Rs .)
        RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ inputs.github-admin-token }}" \
          -d "{\"base_tree\":\"$BASE_TREE\",\"tree\":[{\"path\":\"app.json\",\"mode\":\"100644\",\"type\":\"blob\",\"content\":$CONTENT}]}" \
          https://api.github.com/repos/${{ github.repository }}/git/trees)          
        TREE_SHA_NEW=$(echo "$RESPONSE" | jq -r '.sha')
        echo "TREE_SHA_NEW=$TREE_SHA_NEW" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create a new commit
      id: create-commit
      if: inputs.increment-version == 'true' || inputs.increment-build-number == 'true'
      run: |
        COMMIT_PAYLOAD=$(printf '{"message":"${{ steps.get-commit-message.outputs.commit-message }}","tree":"%s","parents":["%s"]}' "${{ steps.create-tree.outputs.TREE_SHA_NEW }}" "$(git rev-parse HEAD)")

        RESPONSE=$(curl -s -X POST -H "Authorization: token ${{ inputs.github-admin-token }}" \
          -d "$COMMIT_PAYLOAD" \
          https://api.github.com/repos/${{ github.repository }}/git/commits)

        
        COMMIT_SHA=$(echo "$RESPONSE" | jq -r '.sha')
        echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_OUTPUT
      shell: bash

    - name: Update branch reference
      id: update-branch-reference
      if: inputs.increment-version == 'true' || inputs.increment-build-number == 'true'
      run: |
        curl -X PATCH -H "Authorization: token ${{ inputs.github-admin-token }}" \
        -d "{\"sha\": \"${{ steps.create-commit.outputs.COMMIT_SHA }}\", \"force\": true}" \
        https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ inputs.branch-to-push-changes-to }}
      shell: bash