name: Check for Native Code Updates

on:
  pull_request:
    branches:
      - "patch-v*"

jobs:
  check-native-code:
    name: Check for Native Code Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for native code changes
        run: |
          if git diff --name-only HEAD~1 | grep -E '^(ios|android|package.json|Podfile|build.gradle|settings.gradle)'; then
            echo "::set-output name=native-changes::true"
          else
            echo "::set-output name=native-changes::false"
          fi
