name: Trigger on Opened PR from RC branch to Main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
  
jobs:
  submit-staging-build:
    name: Submit Staging Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Check if head branch is rc branch

      - name: Submit Staging Build
        if: startsWith(github.head_ref, 'refs/heads/rc-v')
        uses: ./.github/actions/submit-build
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
          release-channel: staging

      - name: Increment build number
        if: startsWith(github.head_ref, 'refs/heads/rc-v')
        uses: ./.github/actions/increment-version
        with:
          increment-build-number: true
          github-admin-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          branch-to-push-changes-to: ${{github.event.pull_request.base.ref}}
