name: On Main Update from Release Candidate

on:
  pull_request:
    branches:
      main
    types:
      - closed

jobs:
  submit-prod-build:
    name: Submit Prod Build if needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PR Info
        id: check-merged-pr
        uses: ./.github/actions/check-merged-pr
        with:
          expected-base-branch-prefix: main
          expected-head-branch-prefix: rc-v
      
      - name: Submit Prod Build if coming from release candidate branch
        if: steps.check-merged-pr.outputs.result == 'true'
        uses: ./.github/actions/submit-build
        with:
          expo-token: ${{ secrets.EXPO_ACCESS_TOKEN }}
          release-channel: production

      - name: Get current version and build number
        if: steps.check-merged-pr.outputs.result == 'true'
        id: get-current-version-info
        uses: ./.github/actions/get-current-version-info
      
      - name: Get incremented version
        if: steps.check-merged-pr.outputs.result == 'true'
        id: get-incremented-version
        uses: ./.github/actions/increment-version/get-new-version
        with:
          current-version: ${{ steps.get-current-version-info.outputs.version }}
          increment-version-type: minor
      
      # - name: Checkout code
      #   uses: actions/checkout@v4

      - name: Create release candidate branch
        if: steps.check-merged-pr.outputs.result == 'true'
        uses: ./.github/actions/create-branch
        with:
          branch-name: rc-v${{ steps.get-incremented-version.outputs.new-version }}
          base-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set new release candidate version
        if: steps.check-merged-pr.outputs.result == 'true'
        uses: ./.github/actions/set-version
        with:
          github-admin-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          branch-to-push-changes-to: rc-v${{ steps.get-incremented-version.outputs.new-version }}
          version: ${{ steps.get-incremented-version.outputs.new-version }}
          build-number: 1
      