name: Trigger on Opened PR from RC branch to Main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
  
jobs:
  submit-staging-build:
    name: Submit Staging Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Submit Staging Build
        if: startsWith(github.head_ref, 'release/')
        uses: ./.github/actions/submit-build
        with:
          expo-token: ${{ secrets.EXPO_ACCESS_TOKEN }}
          release-channel: staging

      - name: Checkout head branch
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - name: Increment build number
        if: startsWith(github.head_ref, 'release/')
        uses: ./.github/actions/increment-version
        with:
          increment-build-number: true
          github-admin-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          branch-to-push-changes-to: ${{github.event.pull_request.head.ref}}
