name: Trigger on PR merge on patch branch from hotfix branch

on:
  pull_request:
    branches:
      - "patch-v*"
    types:
      - closed

jobs:
  release-ota:
    name: Release Staging OTA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check PR Info
        id: check-merged-pr
        uses: ./.github/actions/check-merged-pr
        with:
          expected-base-branch-prefix: patch-v
          expected-head-branch-prefix: hotfix
      - name: Submit OTA
        uses: ./.github/actions/submit-ota
        if: steps.check-merged-pr.outputs.result == 'true'
        with:
          # TODO: Add expo token to github secrets
          expo-token: ${{ secrets.EXPO_TOKEN }}
          release-channel: staging
          release-message: "${{ github.event.pull_request.title }}"
  open-main-pr:
    name: Open Main PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check PR Info
        id: check-merged-pr
        uses: ./.github/actions/check-merged-pr
        with:
          expected-base-branch-prefix: patch-v
          expected-head-branch-prefix: hotfix
      - name: Open PR
        uses: ./.github/actions/open-pr
        if: steps.check-merged-pr.outputs.result == 'true'
        with:
          template: .github/templates/PATCH_MAIN_PR.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: main
          branch-with-changes: ${{ github.ref_name }}