name: On Prod Update from Release Candidate

on:
  push:
    branches:
      main

jobs:
  submit-prod-build:
    name: Submit Prod Build if needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Submit Prod Build if coming from release candidate branch
        if: startsWith(github.head_ref, 'rc-v')
        uses: ./.github/actions/submit-build
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
          release-channel: production

      # TODO: Incremement version in develop branch
      - name: Get current version and build number
        id: get-current-version-info
        uses: ./.github/actions/get-current-version-info
      
      - name: Get incremented version
        id: get-incremented-version
        uses: ./.github/actions/increment-version/get-new-version
        with:
          current-version: ${{ steps.get-current-version-info.outputs.version }}
          increment-version-type: minor
      
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0
      
      - name: Set new develop version
        uses: ./.github/actions/increment-version
        with:
          github-admin-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          branch-to-push-changes-to: develop
          force-set-version: ${{ steps.get-incremented-version.outputs.new-version }}
          force-set-build-number: 0
      

      # TODO: Create a new release candidate branch if it doesn't exist (from main) & incremement version
      - name: Create release candidate branch
        uses: ./.github/actions/create-branch
        with:
          branch-name: rc-v${{ steps.get-incremented-version.outputs.new-version }}
          base-branch: develop
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          
      - name: Set new release candidate version
        uses: ./.github/actions/increment-version
        with:
          github-admin-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          branch-to-push-changes-to: rc-v${{ steps.get-incremented-version.outputs.new-version }}
          force-set-version: ${{ steps.get-incremented-version.outputs.new-version }}
          force-set-build-number: 0
      