name: OTA Patch Release

on:
  push:
    branches:
      - "patch-v*"
  
jobs:
   
  release-ota:
    name: Release Staging OTA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Release ota with eas updates, set commit message to pr title - new version number
  open-main-pr:
    name: Open Main PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Render PR template
        id: main-pr-template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/templates/pr-patch-to-main.md
          vars: |
            branchName: ${{ github.ref_name }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: "Auto PR from ${GITHUB_REF#refs/heads/}"
          body: ${{ steps.main-pr-template.outputs.result }}
  # open-develop-pr:
  #   name: Open Develop PR
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     # Open a PR to develop
  #     - name: Create Pull Request
  #       uses: peter-evans/create-pull-request@v6.1.0
  #       with:

  

  
    