name: OTA Patch Release

on:
  push:
    branches:
      - "patch-v*"
  
jobs:
   
  release-ota:
    name: Release Staging OTA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Release ota with eas updates, set commit message to pr title - new version number
  open-main-pr:
    name: Open Main PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Open PR
        uses: ./.github/actions/open-pr
        with:
          template: .github/templates/pr-patch-to-main.md
          github-token: ${{ secrets.GITHUB_TOKEN }}

  

  
    