name: OTA Patch Release

on:
  push:
    branches:
      - "patch-v*"
  
jobs:
   
  release-ota:
    name: Release Staging OTA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Release ota with eas updates, set commit message to pr title - new version number
  open-main-pr:
    name: Open Main PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Render PR template
        id: main-pr-template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/templates/pr-patch-to-main.md
          vars: |
            branchName: TESTING
      - name: create pull request
        run: gh pr create -B main -H ${{github.ref_name}} --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v6.1.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     base: "main"
      #     # branch: ${{ github.ref_name }}
      #     title: "Auto PR from ${{ github.ref_name }}"
      #     body: ${{ steps.main-pr-template.outputs.result }}



  # open-develop-pr:
  #   name: Open Develop PR
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     # Open a PR to develop
  #     - name: Create Pull Request
  #       uses: peter-evans/create-pull-request@v6.1.0
  #       with:

  

  
    