name: OTA Patch Release

on:
  push:
    branches:
      - "patch-v*"
  
jobs:
   
  release-ota:
    name: Release Staging OTA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Release ota with eas updates, set commit message to pr title - new version number
  open-main-pr:
    name: Open Main PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Write PR body
        id: write-pr-body
        uses: ./.github/actions/write-pr-body
        with:
          template: .github/templates/pr-patch-to-main.md
          vars: |
            branchName: TESTING
      - name: Read PR body from file
        id: read_pr_body
        run: |
          PR_BODY=$(cat ${{ steps.write-pr-body.outputs.pr-body-file-env-name }})
          echo "PR_BODY<<EOF" >> $GITHUB_ENV
          echo "$PR_BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Open PR
        uses: ./.github/actions/open-pr
        with:
          branch-with-changes: ${{github.ref_name}}
          target-branch: main
          pr-title: 'Merge ${{github.ref_name}} into main'
          pr-body: ${{env.PR_BODY}}

      # - name: create pull request
      #   run: gh pr create -B main -H ${{github.ref_name}} --title 'Merge ${{github.ref_name}} into main' --body '${{env.PR_BODY}}'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # open-develop-pr:
  #   name: Open Develop PR
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     # Open a PR to develop
  #     - name: Create Pull Request
  #       uses: peter-evans/create-pull-request@v6.1.0
  #       with:

  

  
    